version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crm_vendas_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: crm_vendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crm_network

volumes:
  mysql_data:
    driver: local

networks:
  crm_network:
    driver: bridge
